### ISSUE TITLE
Doesn't Launch After Updating

### ISSUE THREAD

**Issue by ProfessorCode212** [flathub/me.kozec.syncthingtk#71]
When I try to launch Syncthing-GTK, the following error occurs. It even launched _just before_ I applied the update but it crashed afterwards.

```
~$ flatpak run me.kozec.syncthingtk
Traceback (most recent call last):
  File "/app/bin/syncthing-gtk", line 32, in <module>
    from syncthing_gtk.app import App
  File "/app/lib/python2.7/site-packages/syncthing_gtk/app.py", line 19, in <module>
    from syncthing_gtk.notifications import Notifications, HAS_DESKTOP_NOTIFY
  File "/app/lib/python2.7/site-packages/syncthing_gtk/notifications.py", line 21, in <module>
    gi.require_version('Notify', '0.7')
  File "/app/lib/python2.7/site-packages/gi/__init__.py", line 133, in require_version
    (namespace, version))
ValueError: Namespace Notify not available for version 0.7
```

**OS:** Linux Mint 20
**Version:** 0.9.4.4

**Comment by muelli** [comment]
sorry, my fault. Fixed with 803899e18ce487c95b9c75d497be9bdb22ed3e94
